[package]
name = "drawille-rs"
version = "0.1.0"
authors = ["Clay Boone <tener.hades@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.drawille]
git = "git://github.com/P1start/drawille-rs"
